version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest-node
      - image: circleci/postgres:latest-postgis
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test

    working_directory: ~/GlobeTrotte

    steps:
      - checkout

      - run: echo 'export PATH=/home/circleci/.nimble/bin:$PATH' >> $BASH_ENV
      - run: echo 'export USER="circleci"' >> $BASH_ENV
      - run: ./scripts/setup.sh -g -s -w
      - run: sudo npm i -g pnpm
      - run: pnpm install --shamefully-hoist
      - run: cp .circleci/test.config config/psql.config

      # run tests
      - run: ./pleasew test --show_all_output
      - run: ./pleasew build --show_all_output
      - run: ./pleasew cover --show_all_output //src/turbine/...
      - run: bash <(curl -s https://codecov.io/bash)
      - run: ./scripts/leftover.sh
