version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest-node
      - image: circleci/postgres:latest-postgis
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test

    working_directory: ~/GlobeTrotte

    steps:
      - checkout

      - run: echo 'export CHOOSENIM_NO_ANALYTICS=1' >> $BASH_ENV
      - run: echo 'export PATH=/home/circleci/.nimble/bin:$PATH' >> $BASH_ENV
      - run: echo 'export USER="circleci"' >> $BASH_ENV
      - run: sudo curl -L https://github.com/binhonglee/wings/releases/download/v0.0.2-alpha/wings_64bit_unix -o /usr/bin/wings
      - run: sudo chmod +x /usr/bin/wings
      - run: sudo apt-get update
      - run: sudo apt-get install libssl-dev
      - run: sudo apt-get install shellcheck
      - run: go get winterdrache.de/goformat/goformat
      - run: cp .circleci/test.config config/psql.config
      - run: yarn

      # run tests
      - run: ./pleasew test --show_all_output
      - run: ./pleasew build --show_all_output
      - run: ./pleasew cover --show_all_output //src/turbine/...
      - run: bash <(curl -s https://codecov.io/bash)
      - run: ./scripts/leftover.sh
